version: "3.8"

services:
  db:
    container_name: stt_db
    image: postgres:14.0-alpine 
    ports:
      - 5434:5432
    expose:
      - 5434
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - TZ=Asia/Seoul
    networks:
      - stt_network
    volumes:
      - stt_db_data:/var/lib/postgresql/data/
    env_file:
      - .env

  db_controler:
    container_name: stt_db_controler
    build: .
    command: bash -c "uvicorn main:app --host 0.0.0.0 --port 8000 --reload && alembic upgrade"
    volumes:
      - .:/app
    ports:
      - 55535:8000
    expose:
      - 55535
    networks:
      - stt_network
    env_file:
      - .env
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - db

  pgadmin:
    container_name: stt_pgadmin
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
      - PGADMIN_CONFIG_SERVER_MODE=${PGADMIN_CONFIG_SERVER_MODE}
    ports:
      - 6060:80
    depends_on:
      - db
    networks:
      - stt_network
    env_file:
      - .env
    volumes:
      - stt_pgadmin_data:/var/lib/pgadmin 

  # redis:
  #   image: redis:6-alpine
  #   container_name: stt_db_redis
  #   networks:
  #     - stt_network

  # celery_worker:
  #   build:
  #     context: .
  #     dockerfile: ./compose/local/django/Dockerfile
  #   command: /start-celeryworker
  #   volumes:
  #     - .:/app
  #   env_file:
  #     - ./.env/.dev-sample
  #   depends_on:
  #     - redis
  #     - db
  #     - db_controler
  #   container_name: stt_mnt_celery_worker
  #   networks:
  #     - stt_network

  # celery_beat:
  #   build:
  #     context: .
  #     dockerfile: ./compose/local/django/Dockerfile
  #   command: /start-celerybeat
  #   volumes:
  #     - .:/app
  #   env_file:
  #     - ./.env/.dev-sample
  #   depends_on:
  #     - redis
  #     - db
  #   container_name: stt_mnt_celery_beat
  #   networks:
  #     - stt_network

  # flower:
  #   build:
  #     context: .
  #     dockerfile: ./compose/local/django/Dockerfile
  #   command: /start-flower
  #   volumes:
  #     - .:/app
  #   env_file:
  #     - ./.env/.dev-sample
  #   ports:
  #     - 55535:5555
  #   depends_on:
  #     - redis
  #     - db
  #   container_name: stt_mnt_celery_flower
  #   networks:
  #     - stt_network 
  

networks:
  stt_network:
    driver: bridge

volumes:
  stt_db_data:
  stt_pgadmin_data: