version: "3.8"

services:
  db:
    container_name: stt_db
    image: postgres:14.0-alpine 
    ports:
      - 5434:5432
    expose:
      - 5434
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - TZ=Asia/Seoul
    networks:
      - stt_network
    volumes:
      - stt_db_data
    env_file:
      - .env

  pgadmin:
    container_name: stt_pgadmin
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}
    ports:
      - 6060:80
    depends_on:
      - db
    networks:
      - stt_network
    env_file:
      - .env

  db_controler:
    container_name: stt_db_controler
    build: .
    command: bash -c "uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
    volumes:
      - .:/app
    ports:
      - 55535:8000
    expose:
      - 55535
    depends_on:
      - db
    networks:
      - stt_network
    env_file:
      - .env

networks:
  stt_network:
    driver: bridge

volumes:
  stt_db_data: