version: "3.8"

services:
  db:
    container_name: stt_db
    image: postgres:14.0-alpine 
    ports:
      - 5434:5432
    expose:
      - 5434
    env_file:
      - .env/.dev-sample
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=stt
      - TZ=Asia/Seoul
    networks:
      - stt_network
    volumes:
      - stt_db_data:/var/lib/postgresql/data/

  db_controler:
    container_name: stt_db_controler
    build: 
      context: .
      dockerfile: ./compose/local/fastapi/Dockerfile
    image: stt_db_controler
    command: bash -c "uvicorn main:app --host 0.0.0.0 --port 8000 --reload && alembic upgrade"
    volumes:
      - .:/app
    ports:
      - 55535:8000
    expose:
      - 55535
    networks:
      - stt_network
    env_file:
      - .env/.dev-sample
    depends_on:
      - db

  pgadmin:
    container_name: stt_pgadmin
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
      - PGADMIN_CONFIG_SERVER_MODE=True
    ports:
      - 6060:80
    depends_on:
      - db
    networks:
      - stt_network
    env_file:
      - .env/.dev-sample
    volumes:
      - stt_pgadmin_data:/var/lib/pgadmin 

  redis:
    image: redis:6-alpine
    container_name: stt_db_redis
    networks:
      - stt_network

  celery_worker:
    container_name: stt_db_celery_worker
    build:
      context: .
      dockerfile: ./compose/local/fastapi/Dockerfile
    image: stt_db_celery_worker
    command: /start-celeryworker
    volumes:
      - .:/app
    env_file:
      - .env/.dev-sample
    depends_on:
      - redis
      - db
    networks:
      - stt_network

  celery_beat:
    container_name: stt_db_celery_beat
    build:
      context: .
      dockerfile: ./compose/local/fastapi/Dockerfile
    command: /start-celerybeat
    volumes:
      - .:/app
    env_file:
      - .env/.dev-sample
    depends_on:
      - redis
      - db
    networks:
      - stt_network

  flower:
    container_name: stt_db_celery_flower
    build:
      context: .
      dockerfile: ./compose/local/fastapi/Dockerfile
    command: /start-flower
    volumes:
      - .:/app
    env_file:
      - .env/.dev-sample
    ports:
      - 55536:5555
    depends_on:
      - redis
      - db
    networks:
      - stt_network 
  

networks:
  stt_network:
    driver: bridge

volumes:
  stt_db_data:
  stt_pgadmin_data: