"""Update date field type into datetime

Revision ID: dcc5ddcbc146
Revises: 
Create Date: 2021-10-29 07:31:20.273599

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dcc5ddcbc146'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('channel',
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('server_id', sa.String(), nullable=False),
    sa.Column('ch_total', sa.Integer(), nullable=True),
    sa.Column('ch_grpc', sa.Integer(), nullable=True),
    sa.Column('ch_rest', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('date', 'server_id')
    )
    op.create_index(op.f('ix_channel_date'), 'channel', ['date'], unique=False)
    op.create_index(op.f('ix_channel_server_id'), 'channel', ['server_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_channel_server_id'), table_name='channel')
    op.drop_index(op.f('ix_channel_date'), table_name='channel')
    op.drop_table('channel')
    # ### end Alembic commands ###
